//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.GeoService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocationResult", Namespace="http://assignment.edu/")]
    [System.SerializableAttribute()]
    public partial class LocationResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LatitudeField;
        
        private double LongitudeField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MapResult", Namespace="http://assignment.edu/")]
    [System.SerializableAttribute()]
    public partial class MapResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MapUrlField;
        
        private bool SuccessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MapUrl {
            get {
                return this.MapUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.MapUrlField, value) != true)) {
                    this.MapUrlField = value;
                    this.RaisePropertyChanged("MapUrl");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://assignment.edu/", ConfigurationName="GeoService.GeoLocationWebServiceSoap")]
    public interface GeoLocationWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name address from namespace http://assignment.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/GetLatLong", ReplyAction="*")]
        Assignment.GeoService.GetLatLongResponse GetLatLong(Assignment.GeoService.GetLatLongRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/GetLatLong", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment.GeoService.GetLatLongResponse> GetLatLongAsync(Assignment.GeoService.GetLatLongRequest request);
        
        // CODEGEN: Generating message contract since element name GetMapImageUrlResult from namespace http://assignment.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/GetMapImageUrl", ReplyAction="*")]
        Assignment.GeoService.GetMapImageUrlResponse GetMapImageUrl(Assignment.GeoService.GetMapImageUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/GetMapImageUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment.GeoService.GetMapImageUrlResponse> GetMapImageUrlAsync(Assignment.GeoService.GetMapImageUrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatLongRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatLong", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.GeoService.GetLatLongRequestBody Body;
        
        public GetLatLongRequest() {
        }
        
        public GetLatLongRequest(Assignment.GeoService.GetLatLongRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class GetLatLongRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string address;
        
        public GetLatLongRequestBody() {
        }
        
        public GetLatLongRequestBody(string address) {
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLatLongResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLatLongResponse", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.GeoService.GetLatLongResponseBody Body;
        
        public GetLatLongResponse() {
        }
        
        public GetLatLongResponse(Assignment.GeoService.GetLatLongResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class GetLatLongResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment.GeoService.LocationResult GetLatLongResult;
        
        public GetLatLongResponseBody() {
        }
        
        public GetLatLongResponseBody(Assignment.GeoService.LocationResult GetLatLongResult) {
            this.GetLatLongResult = GetLatLongResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMapImageUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMapImageUrl", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.GeoService.GetMapImageUrlRequestBody Body;
        
        public GetMapImageUrlRequest() {
        }
        
        public GetMapImageUrlRequest(Assignment.GeoService.GetMapImageUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class GetMapImageUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public double latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double longitude;
        
        public GetMapImageUrlRequestBody() {
        }
        
        public GetMapImageUrlRequestBody(double latitude, double longitude) {
            this.latitude = latitude;
            this.longitude = longitude;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMapImageUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMapImageUrlResponse", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.GeoService.GetMapImageUrlResponseBody Body;
        
        public GetMapImageUrlResponse() {
        }
        
        public GetMapImageUrlResponse(Assignment.GeoService.GetMapImageUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class GetMapImageUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Assignment.GeoService.MapResult GetMapImageUrlResult;
        
        public GetMapImageUrlResponseBody() {
        }
        
        public GetMapImageUrlResponseBody(Assignment.GeoService.MapResult GetMapImageUrlResult) {
            this.GetMapImageUrlResult = GetMapImageUrlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GeoLocationWebServiceSoapChannel : Assignment.GeoService.GeoLocationWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeoLocationWebServiceSoapClient : System.ServiceModel.ClientBase<Assignment.GeoService.GeoLocationWebServiceSoap>, Assignment.GeoService.GeoLocationWebServiceSoap {
        
        public GeoLocationWebServiceSoapClient() {
        }
        
        public GeoLocationWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeoLocationWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeoLocationWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeoLocationWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment.GeoService.GetLatLongResponse Assignment.GeoService.GeoLocationWebServiceSoap.GetLatLong(Assignment.GeoService.GetLatLongRequest request) {
            return base.Channel.GetLatLong(request);
        }
        
        public Assignment.GeoService.LocationResult GetLatLong(string address) {
            Assignment.GeoService.GetLatLongRequest inValue = new Assignment.GeoService.GetLatLongRequest();
            inValue.Body = new Assignment.GeoService.GetLatLongRequestBody();
            inValue.Body.address = address;
            Assignment.GeoService.GetLatLongResponse retVal = ((Assignment.GeoService.GeoLocationWebServiceSoap)(this)).GetLatLong(inValue);
            return retVal.Body.GetLatLongResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment.GeoService.GetLatLongResponse> Assignment.GeoService.GeoLocationWebServiceSoap.GetLatLongAsync(Assignment.GeoService.GetLatLongRequest request) {
            return base.Channel.GetLatLongAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment.GeoService.GetLatLongResponse> GetLatLongAsync(string address) {
            Assignment.GeoService.GetLatLongRequest inValue = new Assignment.GeoService.GetLatLongRequest();
            inValue.Body = new Assignment.GeoService.GetLatLongRequestBody();
            inValue.Body.address = address;
            return ((Assignment.GeoService.GeoLocationWebServiceSoap)(this)).GetLatLongAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment.GeoService.GetMapImageUrlResponse Assignment.GeoService.GeoLocationWebServiceSoap.GetMapImageUrl(Assignment.GeoService.GetMapImageUrlRequest request) {
            return base.Channel.GetMapImageUrl(request);
        }
        
        public Assignment.GeoService.MapResult GetMapImageUrl(double latitude, double longitude) {
            Assignment.GeoService.GetMapImageUrlRequest inValue = new Assignment.GeoService.GetMapImageUrlRequest();
            inValue.Body = new Assignment.GeoService.GetMapImageUrlRequestBody();
            inValue.Body.latitude = latitude;
            inValue.Body.longitude = longitude;
            Assignment.GeoService.GetMapImageUrlResponse retVal = ((Assignment.GeoService.GeoLocationWebServiceSoap)(this)).GetMapImageUrl(inValue);
            return retVal.Body.GetMapImageUrlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment.GeoService.GetMapImageUrlResponse> Assignment.GeoService.GeoLocationWebServiceSoap.GetMapImageUrlAsync(Assignment.GeoService.GetMapImageUrlRequest request) {
            return base.Channel.GetMapImageUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment.GeoService.GetMapImageUrlResponse> GetMapImageUrlAsync(double latitude, double longitude) {
            Assignment.GeoService.GetMapImageUrlRequest inValue = new Assignment.GeoService.GetMapImageUrlRequest();
            inValue.Body = new Assignment.GeoService.GetMapImageUrlRequestBody();
            inValue.Body.latitude = latitude;
            inValue.Body.longitude = longitude;
            return ((Assignment.GeoService.GeoLocationWebServiceSoap)(this)).GetMapImageUrlAsync(inValue);
        }
    }
}
