//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment
{


    public partial class CaptchaTryIt
    {

        protected global::System.Web.UI.WebControls.Button RefreshCaptchaButton;

        protected global::System.Web.UI.WebControls.Label CaptchaEncodedText;

        protected global::System.Web.UI.WebControls.Image CaptchaImage;

        protected global::System.Web.UI.WebControls.TextBox CaptchaInput;

        protected global::System.Web.UI.WebControls.Button VerifyCaptchaButton;

        protected global::System.Web.UI.WebControls.Label CaptchaOutput;

    

        
    }
}
