//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment.CaptchaRef {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://assignment.edu/", ConfigurationName="CaptchaRef.CaptchaServiceSoap")]
    public interface CaptchaServiceSoap {
        
        // CODEGEN: Generating message contract since element name GenerateCaptchaResult from namespace http://assignment.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/GenerateCaptcha", ReplyAction="*")]
        Assignment.CaptchaRef.GenerateCaptchaResponse GenerateCaptcha(Assignment.CaptchaRef.GenerateCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/GenerateCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment.CaptchaRef.GenerateCaptchaResponse> GenerateCaptchaAsync(Assignment.CaptchaRef.GenerateCaptchaRequest request);
        
        // CODEGEN: Generating message contract since element name input from namespace http://assignment.edu/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/VerifyCaptcha", ReplyAction="*")]
        Assignment.CaptchaRef.VerifyCaptchaResponse VerifyCaptcha(Assignment.CaptchaRef.VerifyCaptchaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://assignment.edu/VerifyCaptcha", ReplyAction="*")]
        System.Threading.Tasks.Task<Assignment.CaptchaRef.VerifyCaptchaResponse> VerifyCaptchaAsync(Assignment.CaptchaRef.VerifyCaptchaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateCaptchaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateCaptcha", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.CaptchaRef.GenerateCaptchaRequestBody Body;
        
        public GenerateCaptchaRequest() {
        }
        
        public GenerateCaptchaRequest(Assignment.CaptchaRef.GenerateCaptchaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerateCaptchaRequestBody {
        
        public GenerateCaptchaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateCaptchaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateCaptchaResponse", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.CaptchaRef.GenerateCaptchaResponseBody Body;
        
        public GenerateCaptchaResponse() {
        }
        
        public GenerateCaptchaResponse(Assignment.CaptchaRef.GenerateCaptchaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class GenerateCaptchaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateCaptchaResult;
        
        public GenerateCaptchaResponseBody() {
        }
        
        public GenerateCaptchaResponseBody(string GenerateCaptchaResult) {
            this.GenerateCaptchaResult = GenerateCaptchaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCaptchaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCaptcha", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.CaptchaRef.VerifyCaptchaRequestBody Body;
        
        public VerifyCaptchaRequest() {
        }
        
        public VerifyCaptchaRequest(Assignment.CaptchaRef.VerifyCaptchaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class VerifyCaptchaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string input;
        
        public VerifyCaptchaRequestBody() {
        }
        
        public VerifyCaptchaRequestBody(string input) {
            this.input = input;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCaptchaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCaptchaResponse", Namespace="http://assignment.edu/", Order=0)]
        public Assignment.CaptchaRef.VerifyCaptchaResponseBody Body;
        
        public VerifyCaptchaResponse() {
        }
        
        public VerifyCaptchaResponse(Assignment.CaptchaRef.VerifyCaptchaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://assignment.edu/")]
    public partial class VerifyCaptchaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyCaptchaResult;
        
        public VerifyCaptchaResponseBody() {
        }
        
        public VerifyCaptchaResponseBody(bool VerifyCaptchaResult) {
            this.VerifyCaptchaResult = VerifyCaptchaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CaptchaServiceSoapChannel : Assignment.CaptchaRef.CaptchaServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CaptchaServiceSoapClient : System.ServiceModel.ClientBase<Assignment.CaptchaRef.CaptchaServiceSoap>, Assignment.CaptchaRef.CaptchaServiceSoap {
        
        public CaptchaServiceSoapClient() {
        }
        
        public CaptchaServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CaptchaServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaptchaServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CaptchaServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment.CaptchaRef.GenerateCaptchaResponse Assignment.CaptchaRef.CaptchaServiceSoap.GenerateCaptcha(Assignment.CaptchaRef.GenerateCaptchaRequest request) {
            return base.Channel.GenerateCaptcha(request);
        }
        
        public string GenerateCaptcha() {
            Assignment.CaptchaRef.GenerateCaptchaRequest inValue = new Assignment.CaptchaRef.GenerateCaptchaRequest();
            inValue.Body = new Assignment.CaptchaRef.GenerateCaptchaRequestBody();
            Assignment.CaptchaRef.GenerateCaptchaResponse retVal = ((Assignment.CaptchaRef.CaptchaServiceSoap)(this)).GenerateCaptcha(inValue);
            return retVal.Body.GenerateCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment.CaptchaRef.GenerateCaptchaResponse> Assignment.CaptchaRef.CaptchaServiceSoap.GenerateCaptchaAsync(Assignment.CaptchaRef.GenerateCaptchaRequest request) {
            return base.Channel.GenerateCaptchaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment.CaptchaRef.GenerateCaptchaResponse> GenerateCaptchaAsync() {
            Assignment.CaptchaRef.GenerateCaptchaRequest inValue = new Assignment.CaptchaRef.GenerateCaptchaRequest();
            inValue.Body = new Assignment.CaptchaRef.GenerateCaptchaRequestBody();
            return ((Assignment.CaptchaRef.CaptchaServiceSoap)(this)).GenerateCaptchaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Assignment.CaptchaRef.VerifyCaptchaResponse Assignment.CaptchaRef.CaptchaServiceSoap.VerifyCaptcha(Assignment.CaptchaRef.VerifyCaptchaRequest request) {
            return base.Channel.VerifyCaptcha(request);
        }
        
        public bool VerifyCaptcha(string input) {
            Assignment.CaptchaRef.VerifyCaptchaRequest inValue = new Assignment.CaptchaRef.VerifyCaptchaRequest();
            inValue.Body = new Assignment.CaptchaRef.VerifyCaptchaRequestBody();
            inValue.Body.input = input;
            Assignment.CaptchaRef.VerifyCaptchaResponse retVal = ((Assignment.CaptchaRef.CaptchaServiceSoap)(this)).VerifyCaptcha(inValue);
            return retVal.Body.VerifyCaptchaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Assignment.CaptchaRef.VerifyCaptchaResponse> Assignment.CaptchaRef.CaptchaServiceSoap.VerifyCaptchaAsync(Assignment.CaptchaRef.VerifyCaptchaRequest request) {
            return base.Channel.VerifyCaptchaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Assignment.CaptchaRef.VerifyCaptchaResponse> VerifyCaptchaAsync(string input) {
            Assignment.CaptchaRef.VerifyCaptchaRequest inValue = new Assignment.CaptchaRef.VerifyCaptchaRequest();
            inValue.Body = new Assignment.CaptchaRef.VerifyCaptchaRequestBody();
            inValue.Body.input = input;
            return ((Assignment.CaptchaRef.CaptchaServiceSoap)(this)).VerifyCaptchaAsync(inValue);
        }
    }
}
